/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainCreateRouteImport } from './routes/_main/_create'
import { Route as MainProfileIndexRouteImport } from './routes/_main/profile/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as MainProfileEditRouteImport } from './routes/_main/profile/edit'
import { Route as MainSetupIdIndexRouteImport } from './routes/_main/setup/$id/index'
import { Route as MainCreateCreateIndexRouteImport } from './routes/_main/_create/create/index'
import { Route as AdminAdminUsersIndexRouteImport } from './routes/_admin/admin/users/index'
import { Route as AdminAdminSetupsIndexRouteImport } from './routes/_admin/admin/setups/index'
import { Route as AdminAdminImagesIndexRouteImport } from './routes/_admin/admin/images/index'
import { Route as AdminAdminCategoriesIndexRouteImport } from './routes/_admin/admin/categories/index'
import { Route as MainSetupIdEditRouteImport } from './routes/_main/setup/$id/edit'
import { Route as MainCreateCreateIdTagsRouteImport } from './routes/_main/_create/create/$id/tags'
import { Route as MainCreateCreateIdReviewRouteImport } from './routes/_main/_create/create/$id/review'
import { Route as MainCreateCreateIdInfoRouteImport } from './routes/_main/_create/create/$id/info'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainCreateRoute = MainCreateRouteImport.update({
  id: '/_create',
  getParentRoute: () => MainRoute,
} as any)
const MainProfileIndexRoute = MainProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => MainRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MainProfileEditRoute = MainProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => MainRoute,
} as any)
const MainSetupIdIndexRoute = MainSetupIdIndexRouteImport.update({
  id: '/setup/$id/',
  path: '/setup/$id/',
  getParentRoute: () => MainRoute,
} as any)
const MainCreateCreateIndexRoute = MainCreateCreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => MainCreateRoute,
} as any)
const AdminAdminUsersIndexRoute = AdminAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSetupsIndexRoute = AdminAdminSetupsIndexRouteImport.update({
  id: '/admin/setups/',
  path: '/admin/setups/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminImagesIndexRoute = AdminAdminImagesIndexRouteImport.update({
  id: '/admin/images/',
  path: '/admin/images/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCategoriesIndexRoute =
  AdminAdminCategoriesIndexRouteImport.update({
    id: '/admin/categories/',
    path: '/admin/categories/',
    getParentRoute: () => AdminRoute,
  } as any)
const MainSetupIdEditRoute = MainSetupIdEditRouteImport.update({
  id: '/setup/$id/edit',
  path: '/setup/$id/edit',
  getParentRoute: () => MainRoute,
} as any)
const MainCreateCreateIdTagsRoute = MainCreateCreateIdTagsRouteImport.update({
  id: '/create/$id/tags',
  path: '/create/$id/tags',
  getParentRoute: () => MainCreateRoute,
} as any)
const MainCreateCreateIdReviewRoute =
  MainCreateCreateIdReviewRouteImport.update({
    id: '/create/$id/review',
    path: '/create/$id/review',
    getParentRoute: () => MainCreateRoute,
  } as any)
const MainCreateCreateIdInfoRoute = MainCreateCreateIdInfoRouteImport.update({
  id: '/create/$id/info',
  path: '/create/$id/info',
  getParentRoute: () => MainCreateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/login/': typeof LoginIndexRoute
  '/profile/edit': typeof MainProfileEditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/profile/': typeof MainProfileIndexRoute
  '/setup/$id/edit': typeof MainSetupIdEditRoute
  '/admin/categories/': typeof AdminAdminCategoriesIndexRoute
  '/admin/images/': typeof AdminAdminImagesIndexRoute
  '/admin/setups/': typeof AdminAdminSetupsIndexRoute
  '/admin/users/': typeof AdminAdminUsersIndexRoute
  '/create/': typeof MainCreateCreateIndexRoute
  '/setup/$id/': typeof MainSetupIdIndexRoute
  '/create/$id/info': typeof MainCreateCreateIdInfoRoute
  '/create/$id/review': typeof MainCreateCreateIdReviewRoute
  '/create/$id/tags': typeof MainCreateCreateIdTagsRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile/edit': typeof MainProfileEditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AdminAdminIndexRoute
  '/profile': typeof MainProfileIndexRoute
  '/setup/$id/edit': typeof MainSetupIdEditRoute
  '/admin/categories': typeof AdminAdminCategoriesIndexRoute
  '/admin/images': typeof AdminAdminImagesIndexRoute
  '/admin/setups': typeof AdminAdminSetupsIndexRoute
  '/admin/users': typeof AdminAdminUsersIndexRoute
  '/create': typeof MainCreateCreateIndexRoute
  '/setup/$id': typeof MainSetupIdIndexRoute
  '/create/$id/info': typeof MainCreateCreateIdInfoRoute
  '/create/$id/review': typeof MainCreateCreateIdReviewRoute
  '/create/$id/tags': typeof MainCreateCreateIdTagsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_main/_create': typeof MainCreateRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_main/profile/edit': typeof MainProfileEditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_main/profile/': typeof MainProfileIndexRoute
  '/_main/setup/$id/edit': typeof MainSetupIdEditRoute
  '/_admin/admin/categories/': typeof AdminAdminCategoriesIndexRoute
  '/_admin/admin/images/': typeof AdminAdminImagesIndexRoute
  '/_admin/admin/setups/': typeof AdminAdminSetupsIndexRoute
  '/_admin/admin/users/': typeof AdminAdminUsersIndexRoute
  '/_main/_create/create/': typeof MainCreateCreateIndexRoute
  '/_main/setup/$id/': typeof MainSetupIdIndexRoute
  '/_main/_create/create/$id/info': typeof MainCreateCreateIdInfoRoute
  '/_main/_create/create/$id/review': typeof MainCreateCreateIdReviewRoute
  '/_main/_create/create/$id/tags': typeof MainCreateCreateIdTagsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/profile/edit'
    | '/api/auth/$'
    | '/admin/'
    | '/profile/'
    | '/setup/$id/edit'
    | '/admin/categories/'
    | '/admin/images/'
    | '/admin/setups/'
    | '/admin/users/'
    | '/create/'
    | '/setup/$id/'
    | '/create/$id/info'
    | '/create/$id/review'
    | '/create/$id/tags'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile/edit'
    | '/api/auth/$'
    | '/admin'
    | '/profile'
    | '/setup/$id/edit'
    | '/admin/categories'
    | '/admin/images'
    | '/admin/setups'
    | '/admin/users'
    | '/create'
    | '/setup/$id'
    | '/create/$id/info'
    | '/create/$id/review'
    | '/create/$id/tags'
  id:
    | '__root__'
    | '/_admin'
    | '/_main'
    | '/_main/_create'
    | '/_main/'
    | '/login/'
    | '/_main/profile/edit'
    | '/api/auth/$'
    | '/_admin/admin/'
    | '/_main/profile/'
    | '/_main/setup/$id/edit'
    | '/_admin/admin/categories/'
    | '/_admin/admin/images/'
    | '/_admin/admin/setups/'
    | '/_admin/admin/users/'
    | '/_main/_create/create/'
    | '/_main/setup/$id/'
    | '/_main/_create/create/$id/info'
    | '/_main/_create/create/$id/review'
    | '/_main/_create/create/$id/tags'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_create': {
      id: '/_main/_create'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainCreateRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/profile/': {
      id: '/_main/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof MainProfileIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/profile/edit': {
      id: '/_main/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof MainProfileEditRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/setup/$id/': {
      id: '/_main/setup/$id/'
      path: '/setup/$id'
      fullPath: '/setup/$id/'
      preLoaderRoute: typeof MainSetupIdIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_create/create/': {
      id: '/_main/_create/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof MainCreateCreateIndexRouteImport
      parentRoute: typeof MainCreateRoute
    }
    '/_admin/admin/users/': {
      id: '/_admin/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminAdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/setups/': {
      id: '/_admin/admin/setups/'
      path: '/admin/setups'
      fullPath: '/admin/setups/'
      preLoaderRoute: typeof AdminAdminSetupsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/images/': {
      id: '/_admin/admin/images/'
      path: '/admin/images'
      fullPath: '/admin/images/'
      preLoaderRoute: typeof AdminAdminImagesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/categories/': {
      id: '/_admin/admin/categories/'
      path: '/admin/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminAdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_main/setup/$id/edit': {
      id: '/_main/setup/$id/edit'
      path: '/setup/$id/edit'
      fullPath: '/setup/$id/edit'
      preLoaderRoute: typeof MainSetupIdEditRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_create/create/$id/tags': {
      id: '/_main/_create/create/$id/tags'
      path: '/create/$id/tags'
      fullPath: '/create/$id/tags'
      preLoaderRoute: typeof MainCreateCreateIdTagsRouteImport
      parentRoute: typeof MainCreateRoute
    }
    '/_main/_create/create/$id/review': {
      id: '/_main/_create/create/$id/review'
      path: '/create/$id/review'
      fullPath: '/create/$id/review'
      preLoaderRoute: typeof MainCreateCreateIdReviewRouteImport
      parentRoute: typeof MainCreateRoute
    }
    '/_main/_create/create/$id/info': {
      id: '/_main/_create/create/$id/info'
      path: '/create/$id/info'
      fullPath: '/create/$id/info'
      preLoaderRoute: typeof MainCreateCreateIdInfoRouteImport
      parentRoute: typeof MainCreateRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminCategoriesIndexRoute: typeof AdminAdminCategoriesIndexRoute
  AdminAdminImagesIndexRoute: typeof AdminAdminImagesIndexRoute
  AdminAdminSetupsIndexRoute: typeof AdminAdminSetupsIndexRoute
  AdminAdminUsersIndexRoute: typeof AdminAdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminCategoriesIndexRoute: AdminAdminCategoriesIndexRoute,
  AdminAdminImagesIndexRoute: AdminAdminImagesIndexRoute,
  AdminAdminSetupsIndexRoute: AdminAdminSetupsIndexRoute,
  AdminAdminUsersIndexRoute: AdminAdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MainCreateRouteChildren {
  MainCreateCreateIndexRoute: typeof MainCreateCreateIndexRoute
  MainCreateCreateIdInfoRoute: typeof MainCreateCreateIdInfoRoute
  MainCreateCreateIdReviewRoute: typeof MainCreateCreateIdReviewRoute
  MainCreateCreateIdTagsRoute: typeof MainCreateCreateIdTagsRoute
}

const MainCreateRouteChildren: MainCreateRouteChildren = {
  MainCreateCreateIndexRoute: MainCreateCreateIndexRoute,
  MainCreateCreateIdInfoRoute: MainCreateCreateIdInfoRoute,
  MainCreateCreateIdReviewRoute: MainCreateCreateIdReviewRoute,
  MainCreateCreateIdTagsRoute: MainCreateCreateIdTagsRoute,
}

const MainCreateRouteWithChildren = MainCreateRoute._addFileChildren(
  MainCreateRouteChildren,
)

interface MainRouteChildren {
  MainCreateRoute: typeof MainCreateRouteWithChildren
  MainIndexRoute: typeof MainIndexRoute
  MainProfileEditRoute: typeof MainProfileEditRoute
  MainProfileIndexRoute: typeof MainProfileIndexRoute
  MainSetupIdEditRoute: typeof MainSetupIdEditRoute
  MainSetupIdIndexRoute: typeof MainSetupIdIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainCreateRoute: MainCreateRouteWithChildren,
  MainIndexRoute: MainIndexRoute,
  MainProfileEditRoute: MainProfileEditRoute,
  MainProfileIndexRoute: MainProfileIndexRoute,
  MainSetupIdEditRoute: MainSetupIdEditRoute,
  MainSetupIdIndexRoute: MainSetupIdIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  MainRoute: MainRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
