/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainCreateRouteImport } from './routes/_main/_create'
import { Route as ApiSetupImageUploadRouteImport } from './routes/api/setup-image/upload'
import { Route as ApiSetupImageDeleteRouteImport } from './routes/api/setup-image/delete'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as MainCreateCreateIndexRouteImport } from './routes/_main/_create/create/index'
import { Route as MainCreateCreateIdTagsRouteImport } from './routes/_main/_create/create/$id/tags'
import { Route as MainCreateCreateIdReviewRouteImport } from './routes/_main/_create/create/$id/review'
import { Route as MainCreateCreateIdInfoRouteImport } from './routes/_main/_create/create/$id/info'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainCreateRoute = MainCreateRouteImport.update({
  id: '/_create',
  getParentRoute: () => MainRoute,
} as any)
const ApiSetupImageUploadRoute = ApiSetupImageUploadRouteImport.update({
  id: '/api/setup-image/upload',
  path: '/api/setup-image/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupImageDeleteRoute = ApiSetupImageDeleteRouteImport.update({
  id: '/api/setup-image/delete',
  path: '/api/setup-image/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MainCreateCreateIndexRoute = MainCreateCreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => MainCreateRoute,
} as any)
const MainCreateCreateIdTagsRoute = MainCreateCreateIdTagsRouteImport.update({
  id: '/create/$id/tags',
  path: '/create/$id/tags',
  getParentRoute: () => MainCreateRoute,
} as any)
const MainCreateCreateIdReviewRoute =
  MainCreateCreateIdReviewRouteImport.update({
    id: '/create/$id/review',
    path: '/create/$id/review',
    getParentRoute: () => MainCreateRoute,
  } as any)
const MainCreateCreateIdInfoRoute = MainCreateCreateIdInfoRouteImport.update({
  id: '/create/$id/info',
  path: '/create/$id/info',
  getParentRoute: () => MainCreateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/login/': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/setup-image/delete': typeof ApiSetupImageDeleteRoute
  '/api/setup-image/upload': typeof ApiSetupImageUploadRoute
  '/create/': typeof MainCreateCreateIndexRoute
  '/create/$id/info': typeof MainCreateCreateIdInfoRoute
  '/create/$id/review': typeof MainCreateCreateIdReviewRoute
  '/create/$id/tags': typeof MainCreateCreateIdTagsRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/login': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/setup-image/delete': typeof ApiSetupImageDeleteRoute
  '/api/setup-image/upload': typeof ApiSetupImageUploadRoute
  '/create': typeof MainCreateCreateIndexRoute
  '/create/$id/info': typeof MainCreateCreateIdInfoRoute
  '/create/$id/review': typeof MainCreateCreateIdReviewRoute
  '/create/$id/tags': typeof MainCreateCreateIdTagsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_main/_create': typeof MainCreateRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/login/': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/setup-image/delete': typeof ApiSetupImageDeleteRoute
  '/api/setup-image/upload': typeof ApiSetupImageUploadRoute
  '/_main/_create/create/': typeof MainCreateCreateIndexRoute
  '/_main/_create/create/$id/info': typeof MainCreateCreateIdInfoRoute
  '/_main/_create/create/$id/review': typeof MainCreateCreateIdReviewRoute
  '/_main/_create/create/$id/tags': typeof MainCreateCreateIdTagsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/api/auth/$'
    | '/api/setup-image/delete'
    | '/api/setup-image/upload'
    | '/create/'
    | '/create/$id/info'
    | '/create/$id/review'
    | '/create/$id/tags'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/api/setup-image/delete'
    | '/api/setup-image/upload'
    | '/create'
    | '/create/$id/info'
    | '/create/$id/review'
    | '/create/$id/tags'
  id:
    | '__root__'
    | '/_main'
    | '/_main/_create'
    | '/_main/'
    | '/login/'
    | '/api/auth/$'
    | '/api/setup-image/delete'
    | '/api/setup-image/upload'
    | '/_main/_create/create/'
    | '/_main/_create/create/$id/info'
    | '/_main/_create/create/$id/review'
    | '/_main/_create/create/$id/tags'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSetupImageDeleteRoute: typeof ApiSetupImageDeleteRoute
  ApiSetupImageUploadRoute: typeof ApiSetupImageUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/_create': {
      id: '/_main/_create'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainCreateRouteImport
      parentRoute: typeof MainRoute
    }
    '/api/setup-image/upload': {
      id: '/api/setup-image/upload'
      path: '/api/setup-image/upload'
      fullPath: '/api/setup-image/upload'
      preLoaderRoute: typeof ApiSetupImageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup-image/delete': {
      id: '/api/setup-image/delete'
      path: '/api/setup-image/delete'
      fullPath: '/api/setup-image/delete'
      preLoaderRoute: typeof ApiSetupImageDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/_create/create/': {
      id: '/_main/_create/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof MainCreateCreateIndexRouteImport
      parentRoute: typeof MainCreateRoute
    }
    '/_main/_create/create/$id/tags': {
      id: '/_main/_create/create/$id/tags'
      path: '/create/$id/tags'
      fullPath: '/create/$id/tags'
      preLoaderRoute: typeof MainCreateCreateIdTagsRouteImport
      parentRoute: typeof MainCreateRoute
    }
    '/_main/_create/create/$id/review': {
      id: '/_main/_create/create/$id/review'
      path: '/create/$id/review'
      fullPath: '/create/$id/review'
      preLoaderRoute: typeof MainCreateCreateIdReviewRouteImport
      parentRoute: typeof MainCreateRoute
    }
    '/_main/_create/create/$id/info': {
      id: '/_main/_create/create/$id/info'
      path: '/create/$id/info'
      fullPath: '/create/$id/info'
      preLoaderRoute: typeof MainCreateCreateIdInfoRouteImport
      parentRoute: typeof MainCreateRoute
    }
  }
}

interface MainCreateRouteChildren {
  MainCreateCreateIndexRoute: typeof MainCreateCreateIndexRoute
  MainCreateCreateIdInfoRoute: typeof MainCreateCreateIdInfoRoute
  MainCreateCreateIdReviewRoute: typeof MainCreateCreateIdReviewRoute
  MainCreateCreateIdTagsRoute: typeof MainCreateCreateIdTagsRoute
}

const MainCreateRouteChildren: MainCreateRouteChildren = {
  MainCreateCreateIndexRoute: MainCreateCreateIndexRoute,
  MainCreateCreateIdInfoRoute: MainCreateCreateIdInfoRoute,
  MainCreateCreateIdReviewRoute: MainCreateCreateIdReviewRoute,
  MainCreateCreateIdTagsRoute: MainCreateCreateIdTagsRoute,
}

const MainCreateRouteWithChildren = MainCreateRoute._addFileChildren(
  MainCreateRouteChildren,
)

interface MainRouteChildren {
  MainCreateRoute: typeof MainCreateRouteWithChildren
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainCreateRoute: MainCreateRouteWithChildren,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSetupImageDeleteRoute: ApiSetupImageDeleteRoute,
  ApiSetupImageUploadRoute: ApiSetupImageUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
